### ISSUE TITLE
update GNOME runtime to 3.38

### ISSUE THREAD

**Issue by eszlari** [flathub/org.gnome.gitlab.YaLTeR.VideoTrimmer#1]

**Comment by YaLTeR** [comment]
Anything wrong with 3.36?

**Comment by eszlari** [comment]
No, but this way, new flatpak user have to download fewer runtimes and 3.38 is also based on the new freedesktop runtime 20.08.

**Comment by YaLTeR** [comment]
Fair, although it depends on how many other apps have updated to the new runtime. :) Maybe I'll update it with the next Video Trimmer update whenever that happens.

**Comment by eszlari** [comment]
Don't forget, that the freedesktop runtime also provides hardware support (mesa, libva) for both the GNOME and KDE runtime through extensions (`org.freedesktop.Platform.GL.default`, `org.freedesktop.Platform.VAAPI.Intel`). While they support 19.08 for two years (till 21.08 comes out), the manpower is limited and newer runtimes are more up-to-date, e.g. as of now: 19.08 has mesa 20.1.2 + llvm 9.0.1 and 20.08 has mesa 20.1.5 + llvm 10.0.1.
